In [13]:
import polars as pl
import polars.selectors as cs

## Item Data

In [3]:
sushi_path = "./data/sushi3.idata"
df = pl.read_csv(
    sushi_path, separator="\t", has_header=False, 
    new_columns=[
        "id", "name", "style", "major_group",
        "minor_group", "oiliness", "eaten_frequency",
        "price", "sold_frequency"
    ]
)

df.head()

shape: (5, 9)
┌─────┬────────┬───────┬─────────────┬───┬──────────┬─────────────────┬──────────┬────────────────┐
│ id  ┆ name   ┆ style ┆ major_group ┆ … ┆ oiliness ┆ eaten_frequency ┆ price    ┆ sold_frequency │
│ --- ┆ ---    ┆ ---   ┆ ---         ┆   ┆ ---      ┆ ---             ┆ ---      ┆ ---            │
│ i64 ┆ str    ┆ i64   ┆ i64         ┆   ┆ f64      ┆ f64             ┆ f64      ┆ f64            │
╞═════╪════════╪═══════╪═════════════╪═══╪══════════╪═════════════════╪══════════╪════════════════╡
│ 0   ┆ ebi    ┆ 1     ┆ 0           ┆ … ┆ 2.728978 ┆ 2.138422        ┆ 1.83842  ┆ 0.84           │
│ 1   ┆ anago  ┆ 1     ┆ 0           ┆ … ┆ 0.926384 ┆ 1.990228        ┆ 1.992459 ┆ 0.88           │
│ 2   ┆ maguro ┆ 1     ┆ 0           ┆ … ┆ 1.769559 ┆ 2.348506        ┆ 1.874725 ┆ 0.88           │
│ 3   ┆ ika    ┆ 1     ┆ 0           ┆ … ┆ 2.688401 ┆ 2.04324         ┆ 1.515152 ┆ 0.92           │
│ 4   ┆ uni    ┆ 1     ┆ 0           ┆ … ┆ 0.813043 ┆ 1.643478        ┆ 3.287282 ┆ 0.88           │
└─────┴────────┴───────┴─────────────┴───┴──────────┴─────────────────┴──────────┴────────────────┘

In [4]:
nominal_fields = ["minor_group"]

df[nominal_fields].to_dummies(drop_first=True)

shape: (100, 11)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ minor_gro ┆ minor_gro ┆ minor_gro ┆ minor_gro ┆ … ┆ minor_gro ┆ minor_gro ┆ minor_gro ┆ minor_gr │
│ up_0      ┆ up_1      ┆ up_10     ┆ up_11     ┆   ┆ up_5      ┆ up_7      ┆ up_8      ┆ oup_9    │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ u8        ┆ u8        ┆ u8        ┆ u8        ┆   ┆ u8        ┆ u8        ┆ u8        ┆ u8       │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0         ┆ 0         ┆ 0         ┆ 0         ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0        │
│ 0         ┆ 0         ┆ 0         ┆ 0         ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0        │
│ 0         ┆ 1         ┆ 0         ┆ 0         ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0        │
│ 0         ┆ 0         ┆ 0         ┆ 0         ┆ … ┆ 1         ┆ 0         ┆ 0         ┆ 0        │
│ 0         ┆ 0         ┆ 0         ┆ 0         ┆ … ┆ 0         ┆ 0         ┆ 1         ┆ 0        │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 0         ┆ 0         ┆ 0         ┆ 0         ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0        │
│ 1         ┆ 0         ┆ 0         ┆ 0         ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0        │
│ 0         ┆ 0         ┆ 0         ┆ 0         ┆ … ┆ 0         ┆ 0         ┆ 1         ┆ 0        │
│ 1         ┆ 0         ┆ 0         ┆ 0         ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0        │
│ 0         ┆ 0         ┆ 0         ┆ 0         ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0        │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [5]:
numerical_fields = ["oiliness", "eaten_frequency", "price", "sold_frequency"]

df.select(
    (pl.col(numerical_fields) - pl.col(numerical_fields).min()) / (pl.col(numerical_fields).max() - pl.col(numerical_fields).min())
)

shape: (100, 4)
┌──────────┬─────────────────┬──────────┬────────────────┐
│ oiliness ┆ eaten_frequency ┆ price    ┆ sold_frequency │
│ ---      ┆ ---             ┆ ---      ┆ ---            │
│ f64      ┆ f64             ┆ f64      ┆ f64            │
╞══════════╪═════════════════╪══════════╪════════════════╡
│ 0.685661 ┆ 0.891743        ┆ 0.240548 ┆ 0.909091       │
│ 0.119924 ┆ 0.815379        ┆ 0.284743 ┆ 0.954545       │
│ 0.384551 ┆ 1.0             ┆ 0.250964 ┆ 0.954545       │
│ 0.672926 ┆ 0.842696        ┆ 0.1478   ┆ 1.0            │
│ 0.084352 ┆ 0.636698        ┆ 0.656236 ┆ 0.954545       │
│ …        ┆ …               ┆ …        ┆ …              │
│ 0.645182 ┆ 0.353931        ┆ 0.0      ┆ 0.0            │
│ 0.447643 ┆ 0.305113        ┆ 0.0      ┆ 0.0            │
│ 0.43701  ┆ 0.018109        ┆ 0.143453 ┆ 0.0            │
│ 0.50709  ┆ 0.105863        ┆ 0.0      ┆ 0.0            │
│ 0.387583 ┆ 0.164576        ┆ 0.071727 ┆ 0.0            │
└──────────┴─────────────────┴──────────┴────────────────┘

In [6]:
df_prep = df.sort(
    "id"
).drop(
    ["id", "name", "major_group", "minor_group"]
).with_columns(
    (pl.col(numerical_fields) - pl.col(numerical_fields).min()) / (pl.col(numerical_fields).max() - pl.col(numerical_fields).min())
).with_columns(
    df[nominal_fields].to_dummies(drop_first=True)
)

df_prep.head()

shape: (5, 16)
┌───────┬──────────┬────────────┬──────────┬───┬────────────┬────────────┬────────────┬────────────┐
│ style ┆ oiliness ┆ eaten_freq ┆ price    ┆ … ┆ minor_grou ┆ minor_grou ┆ minor_grou ┆ minor_grou │
│ ---   ┆ ---      ┆ uency      ┆ ---      ┆   ┆ p_5        ┆ p_7        ┆ p_8        ┆ p_9        │
│ i64   ┆ f64      ┆ ---        ┆ f64      ┆   ┆ ---        ┆ ---        ┆ ---        ┆ ---        │
│       ┆          ┆ f64        ┆          ┆   ┆ u8         ┆ u8         ┆ u8         ┆ u8         │
╞═══════╪══════════╪════════════╪══════════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ 1     ┆ 0.685661 ┆ 0.891743   ┆ 0.240548 ┆ … ┆ 0          ┆ 0          ┆ 0          ┆ 0          │
│ 1     ┆ 0.119924 ┆ 0.815379   ┆ 0.284743 ┆ … ┆ 0          ┆ 0          ┆ 0          ┆ 0          │
│ 1     ┆ 0.384551 ┆ 1.0        ┆ 0.250964 ┆ … ┆ 0          ┆ 0          ┆ 0          ┆ 0          │
│ 1     ┆ 0.672926 ┆ 0.842696   ┆ 0.1478   ┆ … ┆ 1          ┆ 0          ┆ 0          ┆ 0          │
│ 1     ┆ 0.084352 ┆ 0.636698   ┆ 0.656236 ┆ … ┆ 0          ┆ 0          ┆ 1          ┆ 0          │
└───────┴──────────┴────────────┴──────────┴───┴────────────┴────────────┴────────────┴────────────┘

In [7]:
df_prep.to_numpy()

array([[1.        , 0.68566117, 0.89174307, ..., 0.        , 0.        ,
        0.        ],
       [1.        , 0.11992393, 0.81537863, ..., 0.        , 0.        ,
        0.        ],
       [1.        , 0.38455113, 1.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [1.        , 0.43701047, 0.01810936, ..., 0.        , 1.        ,
        0.        ],
       [1.        , 0.50708956, 0.10586281, ..., 0.        , 0.        ,
        0.        ],
       [1.        , 0.38758343, 0.16457594, ..., 0.        , 0.        ,
        0.        ]], shape=(100, 16))

In [8]:
df_inds = df["id"].sort().to_list()

df_inds

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99]

## Preference Data

In [ ]:
sushi_path = "./data/sushi3a.5000.10.order"
df = pl.read_csv(
    sushi_path, separator=" ", has_header=False, skip_lines=1
)

df.head()

shape: (5, 12)
┌──────────┬──────────┬──────────┬──────────┬───┬──────────┬───────────┬───────────┬───────────┐
│ column_1 ┆ column_2 ┆ column_3 ┆ column_4 ┆ … ┆ column_9 ┆ column_10 ┆ column_11 ┆ column_12 │
│ ---      ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---      ┆ ---       ┆ ---       ┆ ---       │
│ i64      ┆ i64      ┆ i64      ┆ i64      ┆   ┆ i64      ┆ i64       ┆ i64       ┆ i64       │
╞══════════╪══════════╪══════════╪══════════╪═══╪══════════╪═══════════╪═══════════╪═══════════╡
│ 0        ┆ 10       ┆ 5        ┆ 0        ┆ … ┆ 8        ┆ 1         ┆ 7         ┆ 2         │
│ 0        ┆ 10       ┆ 0        ┆ 9        ┆ … ┆ 8        ┆ 1         ┆ 5         ┆ 4         │
│ 0        ┆ 10       ┆ 7        ┆ 0        ┆ … ┆ 5        ┆ 1         ┆ 9         ┆ 6         │
│ 0        ┆ 10       ┆ 4        ┆ 5        ┆ … ┆ 1        ┆ 6         ┆ 8         ┆ 9         │
│ 0        ┆ 10       ┆ 8        ┆ 6        ┆ … ┆ 2        ┆ 7         ┆ 4         ┆ 1         │
└──────────┴──────────┴──────────┴──────────┴───┴──────────┴───────────┴───────────┴───────────┘

In [15]:
df.select(
    cs.exclude(cs.by_index([0, 1]))
).to_numpy()

array([[5, 0, 3, ..., 1, 7, 2],
       [0, 9, 6, ..., 1, 5, 4],
       [7, 0, 2, ..., 1, 9, 6],
       ...,
       [7, 2, 4, ..., 0, 8, 9],
       [7, 2, 3, ..., 9, 6, 4],
       [0, 5, 3, ..., 9, 8, 1]], shape=(5000, 10))