In [1]:
import polars as pl
import numpy as np
import pickle
import itertools
from joblib import Parallel, delayed

In [7]:
with open("data/pref_distances.pickle", 'rb') as file:
    furthest_ranks = pickle.load(file)

len(furthest_ranks)

46

In [3]:
sushi_path = "./data/sushi3.idata"
sushi_df = pl.read_csv(
    sushi_path, separator="\t", has_header=False, 
    new_columns=[
        "id", "name", "style", "major_group",
        "minor_group", "oiliness", "eaten_frequency",
        "price", "sold_frequency"
    ]
)

sushi_df.tail()

shape: (5, 9)
┌─────┬──────────┬───────┬─────────────┬───┬──────────┬─────────────────┬───────┬────────────────┐
│ id  ┆ name     ┆ style ┆ major_group ┆ … ┆ oiliness ┆ eaten_frequency ┆ price ┆ sold_frequency │
│ --- ┆ ---      ┆ ---   ┆ ---         ┆   ┆ ---      ┆ ---             ┆ ---   ┆ ---            │
│ i64 ┆ str      ┆ i64   ┆ i64         ┆   ┆ f64      ┆ f64             ┆ f64   ┆ f64            │
╞═════╪══════════╪═══════╪═════════════╪═══╪══════════╪═════════════════╪═══════╪════════════════╡
│ 95  ┆ karei    ┆ 1     ┆ 0           ┆ … ┆ 2.6      ┆ 1.094737        ┆ 1.0   ┆ 0.04           │
│ 96  ┆ hiramasa ┆ 1     ┆ 0           ┆ … ┆ 1.970588 ┆ 1.0             ┆ 1.0   ┆ 0.04           │
│ 97  ┆ namako   ┆ 1     ┆ 0           ┆ … ┆ 1.936709 ┆ 0.443038        ┆ 1.5   ┆ 0.04           │
│ 98  ┆ shishamo ┆ 1     ┆ 0           ┆ … ┆ 2.16     ┆ 0.613333        ┆ 1.0   ┆ 0.04           │
│ 99  ┆ kaki     ┆ 1     ┆ 0           ┆ … ┆ 1.779221 ┆ 0.727273        ┆ 1.25  ┆ 0.04           │
└─────┴──────────┴───────┴─────────────┴───┴──────────┴─────────────────┴───────┴────────────────┘

In [4]:
def prep_sushi(df, nominal_fields, numerical_fields, drop_fields, num_rows, id_field = "id"):
    df = df.limit(
        num_rows
    ).sort(
        id_field
    )
    arr = df.drop(
        drop_fields
    ).with_columns(
        (pl.col(numerical_fields) - pl.col(numerical_fields).min()) / (pl.col(numerical_fields).max() - pl.col(numerical_fields).min())
    ).with_columns(
        df[nominal_fields].to_dummies(drop_first=True)
    ).to_numpy()

    inds = (df[id_field].sort() + 1).to_list()

    return arr, inds

nominal_fields = ["minor_group"]
numerical_fields = ["oiliness", "eaten_frequency", "price", "sold_frequency"]
drop_fields = ["id", "name", "major_group"] + nominal_fields

sushi_arr, sushi_inds = prep_sushi(sushi_df, nominal_fields, numerical_fields, drop_fields, 10)

sushi_arr

array([[1.        , 0.85828263, 0.70201946, 0.2334073 , 0.5       ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [1.        , 0.14765004, 0.49182399, 0.2780176 , 0.75      ,
        0.        , 1.        , 0.        , 0.        , 0.        ,
        0.        ],
       [1.        , 0.48005296, 1.        , 0.24392127, 0.75      ,
        1.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [1.        , 0.84228598, 0.56701463, 0.13978737, 1.        ,
        0.        , 0.        , 1.        , 0.        , 0.        ,
        0.        ],
       [1.        , 0.1029679 , 0.        , 0.65300401, 0.75      ,
        0.        , 0.        , 0.        , 0.        , 1.        ,
        0.        ],
       [1.        , 1.        , 0.10477308, 0.10190094, 0.        ,
        0.        , 0.        , 1.        , 0.        , 0.        ,
        0.        ],
       [1.        , 0.28109149, 0.47655331, 0.48158165, 0.75      ,
        0.        , 0.        , 0.        , 1.        , 0.        ,
        0.        ],
       [1.        , 0.71600302, 0.31593767, 0.        , 0.5       ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        1.        ],
       [1.        , 0.        , 0.58728707, 1.        , 0.25      ,
        1.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [1.        , 0.53699054, 0.60259965, 0.25847357, 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ]])

In [8]:
distances = list(int(dist) for dist in furthest_ranks)
human_utility_flags = [True, False]
human_betas = [1.5, 0.5]
algorithm_betas = [1.5]
algorithm_alphas = [1.5, 0.0]
algorithm_sigmas = [1.5]

p_penalty = 0.321
algo_k = 2
universe = [0] + sushi_inds

NameError: name 'sushi_inds' is not defined

In [7]:
len(furthest_ranks[0])

80

In [7]:
# def process_pair(human_ranks, algo_ranks):
#     utility_arr = np.zeros(11)
#     if use_human_utility:
#         utility_arr[human_ranks[0]] = 1
#     else:
#         utility_arr[algo_ranks[0]] = 1

#     human = TopKMallows(center=human_ranks, k=10, beta=human_beta, p=p_penalty)
#     algo = DiverseTopKMallows(center=algo_ranks, k=algo_k, beta=algo_beta, p=p_penalty, embeddings=sushi_arr, alpha=algo_alpha, sigma=algo_sigma)

#     util = human.collab_utility(algo, universe, utility_arr)

#     return human_ranks, algo_ranks, util

# pairs = furthest_ranks[0]

# res = Parallel(n_jobs=-2, verbose=10)(
#     delayed(process_pair)(*pair) for pair in pairs
# )

In [8]:
universe

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [16]:
if None in furthest_ranks:
    del furthest_ranks[None]

In [17]:
len(furthest_ranks)

46

In [10]:
list(
    itertools.product(
        distances, human_utility_flags, human_betas, algorithm_betas, 
        algorithm_alphas, algorithm_sigmas
    )
)

[(21, True, 1.5, 1.5, 1.5, 1.5),
 (21, True, 1.5, 1.5, 0.0, 1.5),
 (21, True, 0.5, 1.5, 1.5, 1.5),
 (21, True, 0.5, 1.5, 0.0, 1.5),
 (21, False, 1.5, 1.5, 1.5, 1.5),
 (21, False, 1.5, 1.5, 0.0, 1.5),
 (21, False, 0.5, 1.5, 1.5, 1.5),
 (21, False, 0.5, 1.5, 0.0, 1.5),
 (25, True, 1.5, 1.5, 1.5, 1.5),
 (25, True, 1.5, 1.5, 0.0, 1.5),
 (25, True, 0.5, 1.5, 1.5, 1.5),
 (25, True, 0.5, 1.5, 0.0, 1.5),
 (25, False, 1.5, 1.5, 1.5, 1.5),
 (25, False, 1.5, 1.5, 0.0, 1.5),
 (25, False, 0.5, 1.5, 1.5, 1.5),
 (25, False, 0.5, 1.5, 0.0, 1.5),
 (18, True, 1.5, 1.5, 1.5, 1.5),
 (18, True, 1.5, 1.5, 0.0, 1.5),
 (18, True, 0.5, 1.5, 1.5, 1.5),
 (18, True, 0.5, 1.5, 0.0, 1.5),
 (18, False, 1.5, 1.5, 1.5, 1.5),
 (18, False, 1.5, 1.5, 0.0, 1.5),
 (18, False, 0.5, 1.5, 1.5, 1.5),
 (18, False, 0.5, 1.5, 0.0, 1.5),
 (16, True, 1.5, 1.5, 1.5, 1.5),
 (16, True, 1.5, 1.5, 0.0, 1.5),
 (16, True, 0.5, 1.5, 1.5, 1.5),
 (16, True, 0.5, 1.5, 0.0, 1.5),
 (16, False, 1.5, 1.5, 1.5, 1.5),
 (16, False, 1.5, 1.5, 0.0, 1.5),
 (16, False, 0.5, 1.5, 1.5, 1.5),
 (16, False, 0.5, 1.5, 0.0, 1.5),
 (23, True, 1.5, 1.5, 1.5, 1.5),
 (23, True, 1.5, 1.5, 0.0, 1.5),
 (23, True, 0.5, 1.5, 1.5, 1.5),
 (23, True, 0.5, 1.5, 0.0, 1.5),
 (23, False, 1.5, 1.5, 1.5, 1.5),
 (23, False, 1.5, 1.5, 0.0, 1.5),
 (23, False, 0.5, 1.5, 1.5, 1.5),
 (23, False, 0.5, 1.5, 0.0, 1.5),
 (27, True, 1.5, 1.5, 1.5, 1.5),
 (27, True, 1.5, 1.5, 0.0, 1.5),
 (27, True, 0.5, 1.5, 1.5, 1.5),
 (27, True, 0.5, 1.5, 0.0, 1.5),
 (27, False, 1.5, 1.5, 1.5, 1.5),
 (27, False, 1.5, 1.5, 0.0, 1.5),
 (27, False, 0.5, 1.5, 1.5, 1.5),
 (27, False, 0.5, 1.5, 0.0, 1.5),
 (26, True, 1.5, 1.5, 1.5, 1.5),
 (26, True, 1.5, 1.5, 0.0, 1.5),
 (26, True, 0.5, 1.5, 1.5, 1.5),
 (26, True, 0.5, 1.5, 0.0, 1.5),
 (26, False, 1.5, 1.5, 1.5, 1.5),
 (26, False, 1.5, 1.5, 0.0, 1.5),
 (26, False, 0.5, 1.5, 1.5, 1.5),
 (26, False, 0.5, 1.5, 0.0, 1.5),
 (22, True, 1.5, 1.5, 1.5, 1.5),
 (22, True, 1.5, 1.5, 0.0, 1.5),
 (22, True, 0.5, 1.5, 1.5, 1.5),
 (22, True, 0.5, 1.5, 0.0, 1.5),
 (22, False, 1.5, 1.5, 1.5, 1.5),
 (22, False, 1.5, 1.5, 0.0, 1.5),
 (22, False, 0.5, 1.5, 1.5, 1.5),
 (22, False, 0.5, 1.5, 0.0, 1.5),
 (32, True, 1.5, 1.5, 1.5, 1.5),
 (32, True, 1.5, 1.5, 0.0, 1.5),
 (32, True, 0.5, 1.5, 1.5, 1.5),
 (32, True, 0.5, 1.5, 0.0, 1.5),
 (32, False, 1.5, 1.5, 1.5, 1.5),
 (32, False, 1.5, 1.5, 0.0, 1.5),
 (32, False, 0.5, 1.5, 1.5, 1.5),
 (32, False, 0.5, 1.5, 0.0, 1.5),
 (20, True, 1.5, 1.5, 1.5, 1.5),
 (20, True, 1.5, 1.5, 0.0, 1.5),
 (20, True, 0.5, 1.5, 1.5, 1.5),
 (20, True, 0.5, 1.5, 0.0, 1.5),
 (20, False, 1.5, 1.5, 1.5, 1.5),
 (20, False, 1.5, 1.5, 0.0, 1.5),
 (20, False, 0.5, 1.5, 1.5, 1.5),
 (20, False, 0.5, 1.5, 0.0, 1.5),
 (9, True, 1.5, 1.5, 1.5, 1.5),
 (9, True, 1.5, 1.5, 0.0, 1.5),
 (9, True, 0.5, 1.5, 1.5, 1.5),
 (9, True, 0.5, 1.5, 0.0, 1.5),
 (9, False, 1.5, 1.5, 1.5, 1.5),
 (9, False, 1.5, 1.5, 0.0, 1.5),
 (9, False, 0.5, 1.5, 1.5, 1.5),
 (9, False, 0.5, 1.5, 0.0, 1.5),
 (28, True, 1.5, 1.5, 1.5, 1.5),
 (28, True, 1.5, 1.5, 0.0, 1.5),
 (28, True, 0.5, 1.5, 1.5, 1.5),
 (28, True, 0.5, 1.5, 0.0, 1.5),
 (28, False, 1.5, 1.5, 1.5, 1.5),
 (28, False, 1.5, 1.5, 0.0, 1.5),
 (28, False, 0.5, 1.5, 1.5, 1.5),
 (28, False, 0.5, 1.5, 0.0, 1.5),
 (15, True, 1.5, 1.5, 1.5, 1.5),
 (15, True, 1.5, 1.5, 0.0, 1.5),
 (15, True, 0.5, 1.5, 1.5, 1.5),
 (15, True, 0.5, 1.5, 0.0, 1.5),
 (15, False, 1.5, 1.5, 1.5, 1.5),
 (15, False, 1.5, 1.5, 0.0, 1.5),
 (15, False, 0.5, 1.5, 1.5, 1.5),
 (15, False, 0.5, 1.5, 0.0, 1.5),
 (29, True, 1.5, 1.5, 1.5, 1.5),
 (29, True, 1.5, 1.5, 0.0, 1.5),
 (29, True, 0.5, 1.5, 1.5, 1.5),
 (29, True, 0.5, 1.5, 0.0, 1.5),
 (29, False, 1.5, 1.5, 1.5, 1.5),
 (29, False, 1.5, 1.5, 0.0, 1.5),
 (29, False, 0.5, 1.5, 1.5, 1.5),
 (29, False, 0.5, 1.5, 0.0, 1.5),
 (13, True, 1.5, 1.5, 1.5, 1.5),
 (13, True, 1.5, 1.5, 0.0, 1.5),
 (13, True, 0.5, 1.5, 1.5, 1.5),
 (13, True, 0.5, 1.5, 0.0, 1.5),
 (13, False, 1.5, 1.5, 1.5, 1.5),
 (13, False, 1.5, 1.5, 0.0, 1.5),
 (13, False, 0.5, 1.5, 1.5, 1.5),
 (13, False, 0.5, 1.5, 0.0, 1.5),
 (24, True, 1.5, 1.5, 1.5, 1.5),
 (24, True, 1.5, 1.5, 0.0, 1.5),
 (24, True, 0.5, 1.5, 1.5, 1.5),
 (24, True, 0.5, 1.5, 0.0, 1.5),
 (24, False, 1.5, 1.5, 1.5, 1.5),
 (24, False, 1.5, 1.5, 0.0, 1.5),
 (24, False, 0.5, 1.5, 1.5, 1.5),
 (24, False, 0.5, 1.5, 0.0, 1.5),
 (19, True, 1.5, 1.5, 1.5, 1.5),
 (19, True, 1.5, 1.5, 0.0, 1.5),
 (19, True, 0.5, 1.5, 1.5, 1.5),
 (19, True, 0.5, 1.5, 0.0, 1.5),
 (19, False, 1.5, 1.5, 1.5, 1.5),
 (19, False, 1.5, 1.5, 0.0, 1.5),
 (19, False, 0.5, 1.5, 1.5, 1.5),
 (19, False, 0.5, 1.5, 0.0, 1.5),
 (35, True, 1.5, 1.5, 1.5, 1.5),
 (35, True, 1.5, 1.5, 0.0, 1.5),
 (35, True, 0.5, 1.5, 1.5, 1.5),
 (35, True, 0.5, 1.5, 0.0, 1.5),
 (35, False, 1.5, 1.5, 1.5, 1.5),
 (35, False, 1.5, 1.5, 0.0, 1.5),
 (35, False, 0.5, 1.5, 1.5, 1.5),
 (35, False, 0.5, 1.5, 0.0, 1.5),
 (4, True, 1.5, 1.5, 1.5, 1.5),
 (4, True, 1.5, 1.5, 0.0, 1.5),
 (4, True, 0.5, 1.5, 1.5, 1.5),
 (4, True, 0.5, 1.5, 0.0, 1.5),
 (4, False, 1.5, 1.5, 1.5, 1.5),
 (4, False, 1.5, 1.5, 0.0, 1.5),
 (4, False, 0.5, 1.5, 1.5, 1.5),
 (4, False, 0.5, 1.5, 0.0, 1.5),
 (30, True, 1.5, 1.5, 1.5, 1.5),
 (30, True, 1.5, 1.5, 0.0, 1.5),
 (30, True, 0.5, 1.5, 1.5, 1.5),
 (30, True, 0.5, 1.5, 0.0, 1.5),
 (30, False, 1.5, 1.5, 1.5, 1.5),
 (30, False, 1.5, 1.5, 0.0, 1.5),
 (30, False, 0.5, 1.5, 1.5, 1.5),
 (30, False, 0.5, 1.5, 0.0, 1.5),
 (17, True, 1.5, 1.5, 1.5, 1.5),
 (17, True, 1.5, 1.5, 0.0, 1.5),
 (17, True, 0.5, 1.5, 1.5, 1.5),
 (17, True, 0.5, 1.5, 0.0, 1.5),
 (17, False, 1.5, 1.5, 1.5, 1.5),
 (17, False, 1.5, 1.5, 0.0, 1.5),
 (17, False, 0.5, 1.5, 1.5, 1.5),
 (17, False, 0.5, 1.5, 0.0, 1.5),
 (33, True, 1.5, 1.5, 1.5, 1.5),
 (33, True, 1.5, 1.5, 0.0, 1.5),
 (33, True, 0.5, 1.5, 1.5, 1.5),
 (33, True, 0.5, 1.5, 0.0, 1.5),
 (33, False, 1.5, 1.5, 1.5, 1.5),
 (33, False, 1.5, 1.5, 0.0, 1.5),
 (33, False, 0.5, 1.5, 1.5, 1.5),
 (33, False, 0.5, 1.5, 0.0, 1.5),
 (34, True, 1.5, 1.5, 1.5, 1.5),
 (34, True, 1.5, 1.5, 0.0, 1.5),
 (34, True, 0.5, 1.5, 1.5, 1.5),
 (34, True, 0.5, 1.5, 0.0, 1.5),
 (34, False, 1.5, 1.5, 1.5, 1.5),
 (34, False, 1.5, 1.5, 0.0, 1.5),
 (34, False, 0.5, 1.5, 1.5, 1.5),
 (34, False, 0.5, 1.5, 0.0, 1.5),
 (31, True, 1.5, 1.5, 1.5, 1.5),
 (31, True, 1.5, 1.5, 0.0, 1.5),
 (31, True, 0.5, 1.5, 1.5, 1.5),
 (31, True, 0.5, 1.5, 0.0, 1.5),
 (31, False, 1.5, 1.5, 1.5, 1.5),
 (31, False, 1.5, 1.5, 0.0, 1.5),
 (31, False, 0.5, 1.5, 1.5, 1.5),
 (31, False, 0.5, 1.5, 0.0, 1.5),
 (39, True, 1.5, 1.5, 1.5, 1.5),
 (39, True, 1.5, 1.5, 0.0, 1.5),
 (39, True, 0.5, 1.5, 1.5, 1.5),
 (39, True, 0.5, 1.5, 0.0, 1.5),
 (39, False, 1.5, 1.5, 1.5, 1.5),
 (39, False, 1.5, 1.5, 0.0, 1.5),
 (39, False, 0.5, 1.5, 1.5, 1.5),
 (39, False, 0.5, 1.5, 0.0, 1.5),
 (10, True, 1.5, 1.5, 1.5, 1.5),
 (10, True, 1.5, 1.5, 0.0, 1.5),
 (10, True, 0.5, 1.5, 1.5, 1.5),
 (10, True, 0.5, 1.5, 0.0, 1.5),
 (10, False, 1.5, 1.5, 1.5, 1.5),
 (10, False, 1.5, 1.5, 0.0, 1.5),
 (10, False, 0.5, 1.5, 1.5, 1.5),
 (10, False, 0.5, 1.5, 0.0, 1.5),
 (36, True, 1.5, 1.5, 1.5, 1.5),
 (36, True, 1.5, 1.5, 0.0, 1.5),
 (36, True, 0.5, 1.5, 1.5, 1.5),
 (36, True, 0.5, 1.5, 0.0, 1.5),
 (36, False, 1.5, 1.5, 1.5, 1.5),
 (36, False, 1.5, 1.5, 0.0, 1.5),
 (36, False, 0.5, 1.5, 1.5, 1.5),
 (36, False, 0.5, 1.5, 0.0, 1.5),
 (12, True, 1.5, 1.5, 1.5, 1.5),
 (12, True, 1.5, 1.5, 0.0, 1.5),
 (12, True, 0.5, 1.5, 1.5, 1.5),
 (12, True, 0.5, 1.5, 0.0, 1.5),
 (12, False, 1.5, 1.5, 1.5, 1.5),
 (12, False, 1.5, 1.5, 0.0, 1.5),
 (12, False, 0.5, 1.5, 1.5, 1.5),
 (12, False, 0.5, 1.5, 0.0, 1.5),
 (14, True, 1.5, 1.5, 1.5, 1.5),
 (14, True, 1.5, 1.5, 0.0, 1.5),
 (14, True, 0.5, 1.5, 1.5, 1.5),
 (14, True, 0.5, 1.5, 0.0, 1.5),
 (14, False, 1.5, 1.5, 1.5, 1.5),
 (14, False, 1.5, 1.5, 0.0, 1.5),
 (14, False, 0.5, 1.5, 1.5, 1.5),
 (14, False, 0.5, 1.5, 0.0, 1.5),
 (37, True, 1.5, 1.5, 1.5, 1.5),
 (37, True, 1.5, 1.5, 0.0, 1.5),
 (37, True, 0.5, 1.5, 1.5, 1.5),
 (37, True, 0.5, 1.5, 0.0, 1.5),
 (37, False, 1.5, 1.5, 1.5, 1.5),
 (37, False, 1.5, 1.5, 0.0, 1.5),
 (37, False, 0.5, 1.5, 1.5, 1.5),
 (37, False, 0.5, 1.5, 0.0, 1.5),
 (38, True, 1.5, 1.5, 1.5, 1.5),
 (38, True, 1.5, 1.5, 0.0, 1.5),
 (38, True, 0.5, 1.5, 1.5, 1.5),
 (38, True, 0.5, 1.5, 0.0, 1.5),
 (38, False, 1.5, 1.5, 1.5, 1.5),
 (38, False, 1.5, 1.5, 0.0, 1.5),
 (38, False, 0.5, 1.5, 1.5, 1.5),
 (38, False, 0.5, 1.5, 0.0, 1.5),
 (11, True, 1.5, 1.5, 1.5, 1.5),
 (11, True, 1.5, 1.5, 0.0, 1.5),
 (11, True, 0.5, 1.5, 1.5, 1.5),
 (11, True, 0.5, 1.5, 0.0, 1.5),
 (11, False, 1.5, 1.5, 1.5, 1.5),
 (11, False, 1.5, 1.5, 0.0, 1.5),
 (11, False, 0.5, 1.5, 1.5, 1.5),
 (11, False, 0.5, 1.5, 0.0, 1.5),
 (6, True, 1.5, 1.5, 1.5, 1.5),
 (6, True, 1.5, 1.5, 0.0, 1.5),
 (6, True, 0.5, 1.5, 1.5, 1.5),
 (6, True, 0.5, 1.5, 0.0, 1.5),
 (6, False, 1.5, 1.5, 1.5, 1.5),
 (6, False, 1.5, 1.5, 0.0, 1.5),
 (6, False, 0.5, 1.5, 1.5, 1.5),
 (6, False, 0.5, 1.5, 0.0, 1.5),
 (8, True, 1.5, 1.5, 1.5, 1.5),
 (8, True, 1.5, 1.5, 0.0, 1.5),
 (8, True, 0.5, 1.5, 1.5, 1.5),
 (8, True, 0.5, 1.5, 0.0, 1.5),
 (8, False, 1.5, 1.5, 1.5, 1.5),
 (8, False, 1.5, 1.5, 0.0, 1.5),
 (8, False, 0.5, 1.5, 1.5, 1.5),
 (8, False, 0.5, 1.5, 0.0, 1.5),
 (40, True, 1.5, 1.5, 1.5, 1.5),
 (40, True, 1.5, 1.5, 0.0, 1.5),
 (40, True, 0.5, 1.5, 1.5, 1.5),
 (40, True, 0.5, 1.5, 0.0, 1.5),
 (40, False, 1.5, 1.5, 1.5, 1.5),
 (40, False, 1.5, 1.5, 0.0, 1.5),
 (40, False, 0.5, 1.5, 1.5, 1.5),
 (40, False, 0.5, 1.5, 0.0, 1.5),
 (7, True, 1.5, 1.5, 1.5, 1.5),
 (7, True, 1.5, 1.5, 0.0, 1.5),
 (7, True, 0.5, 1.5, 1.5, 1.5),
 (7, True, 0.5, 1.5, 0.0, 1.5),
 (7, False, 1.5, 1.5, 1.5, 1.5),
 (7, False, 1.5, 1.5, 0.0, 1.5),
 (7, False, 0.5, 1.5, 1.5, 1.5),
 (7, False, 0.5, 1.5, 0.0, 1.5),
 (5, True, 1.5, 1.5, 1.5, 1.5),
 (5, True, 1.5, 1.5, 0.0, 1.5),
 (5, True, 0.5, 1.5, 1.5, 1.5),
 (5, True, 0.5, 1.5, 0.0, 1.5),
 (5, False, 1.5, 1.5, 1.5, 1.5),
 (5, False, 1.5, 1.5, 0.0, 1.5),
 (5, False, 0.5, 1.5, 1.5, 1.5),
 (5, False, 0.5, 1.5, 0.0, 1.5),
 (3, True, 1.5, 1.5, 1.5, 1.5),
 (3, True, 1.5, 1.5, 0.0, 1.5),
 (3, True, 0.5, 1.5, 1.5, 1.5),
 (3, True, 0.5, 1.5, 0.0, 1.5),
 (3, False, 1.5, 1.5, 1.5, 1.5),
 (3, False, 1.5, 1.5, 0.0, 1.5),
 (3, False, 0.5, 1.5, 1.5, 1.5),
 (3, False, 0.5, 1.5, 0.0, 1.5),
 (41, True, 1.5, 1.5, 1.5, 1.5),
 (41, True, 1.5, 1.5, 0.0, 1.5),
 (41, True, 0.5, 1.5, 1.5, 1.5),
 (41, True, 0.5, 1.5, 0.0, 1.5),
 (41, False, 1.5, 1.5, 1.5, 1.5),
 (41, False, 1.5, 1.5, 0.0, 1.5),
 (41, False, 0.5, 1.5, 1.5, 1.5),
 (41, False, 0.5, 1.5, 0.0, 1.5),
 (2, True, 1.5, 1.5, 1.5, 1.5),
 (2, True, 1.5, 1.5, 0.0, 1.5),
 (2, True, 0.5, 1.5, 1.5, 1.5),
 (2, True, 0.5, 1.5, 0.0, 1.5),
 (2, False, 1.5, 1.5, 1.5, 1.5),
 (2, False, 1.5, 1.5, 0.0, 1.5),
 (2, False, 0.5, 1.5, 1.5, 1.5),
 (2, False, 0.5, 1.5, 0.0, 1.5),
 (1, True, 1.5, 1.5, 1.5, 1.5),
 (1, True, 1.5, 1.5, 0.0, 1.5),
 (1, True, 0.5, 1.5, 1.5, 1.5),
 (1, True, 0.5, 1.5, 0.0, 1.5),
 (1, False, 1.5, 1.5, 1.5, 1.5),
 (1, False, 1.5, 1.5, 0.0, 1.5),
 (1, False, 0.5, 1.5, 1.5, 1.5),
 (1, False, 0.5, 1.5, 0.0, 1.5),
 (42, True, 1.5, 1.5, 1.5, 1.5),
 (42, True, 1.5, 1.5, 0.0, 1.5),
 (42, True, 0.5, 1.5, 1.5, 1.5),
 (42, True, 0.5, 1.5, 0.0, 1.5),
 (42, False, 1.5, 1.5, 1.5, 1.5),
 (42, False, 1.5, 1.5, 0.0, 1.5),
 (42, False, 0.5, 1.5, 1.5, 1.5),
 (42, False, 0.5, 1.5, 0.0, 1.5),
 (43, True, 1.5, 1.5, 1.5, 1.5),
 (43, True, 1.5, 1.5, 0.0, 1.5),
 (43, True, 0.5, 1.5, 1.5, 1.5),
 (43, True, 0.5, 1.5, 0.0, 1.5),
 (43, False, 1.5, 1.5, 1.5, 1.5),
 (43, False, 1.5, 1.5, 0.0, 1.5),
 (43, False, 0.5, 1.5, 1.5, 1.5),
 (43, False, 0.5, 1.5, 0.0, 1.5),
 (0, True, 1.5, 1.5, 1.5, 1.5),
 (0, True, 1.5, 1.5, 0.0, 1.5),
 (0, True, 0.5, 1.5, 1.5, 1.5),
 (0, True, 0.5, 1.5, 0.0, 1.5),
 (0, False, 1.5, 1.5, 1.5, 1.5),
 (0, False, 1.5, 1.5, 0.0, 1.5),
 (0, False, 0.5, 1.5, 1.5, 1.5),
 (0, False, 0.5, 1.5, 0.0, 1.5),
 (45, True, 1.5, 1.5, 1.5, 1.5),
 (45, True, 1.5, 1.5, 0.0, 1.5),
 (45, True, 0.5, 1.5, 1.5, 1.5),
 (45, True, 0.5, 1.5, 0.0, 1.5),
 (45, False, 1.5, 1.5, 1.5, 1.5),
 (45, False, 1.5, 1.5, 0.0, 1.5),
 (45, False, 0.5, 1.5, 1.5, 1.5),
 (45, False, 0.5, 1.5, 0.0, 1.5),
 (44, True, 1.5, 1.5, 1.5, 1.5),
 (44, True, 1.5, 1.5, 0.0, 1.5),
 (44, True, 0.5, 1.5, 1.5, 1.5),
 (44, True, 0.5, 1.5, 0.0, 1.5),
 (44, False, 1.5, 1.5, 1.5, 1.5),
 (44, False, 1.5, 1.5, 0.0, 1.5),
 (44, False, 0.5, 1.5, 1.5, 1.5),
 (44, False, 0.5, 1.5, 0.0, 1.5)]

In [11]:
from mallows import TopKMallows, DiverseTopKMallows

def process_combo(distance: int, use_human_utility: bool, human_beta: float, algo_beta: float, algo_alpha: float, algo_sigma: float):
    def process_pair(human_ranks, algo_ranks):
        utility_arr = np.zeros(11)
        if use_human_utility:
            utility_arr[human_ranks[0]] = 1
        else:
            utility_arr[algo_ranks[0]] = 1

        human = TopKMallows(center=human_ranks, k=10, beta=human_beta, p=p_penalty)
        algo = DiverseTopKMallows(center=algo_ranks, k=algo_k, beta=algo_beta, p=p_penalty, embeddings=sushi_arr, alpha=algo_alpha, sigma=algo_sigma)

        #print(human_ranks, algo_ranks, universe)
        util = human.collab_utility(algo, universe, utility_arr)

        return human_ranks, algo_ranks, util

    pairs = furthest_ranks[distance]

    pair_res = Parallel(n_jobs=-2, verbose=10)(
        delayed(process_pair)(*pair) for pair in pairs
    )

    return pair_res, distance, use_human_utility, human_beta, algo_beta, algo_alpha, algo_sigma

parameter_combos = list(itertools.product(distances, human_utility_flags, human_betas, algorithm_betas, algorithm_alphas, algorithm_sigmas))

res = Parallel(n_jobs=-2, verbose=10)(
    delayed(process_combo)(*combo) for combo in parameter_combos
)

[Parallel(n_jobs=-2)]: Using backend LokyBackend with 11 concurrent workers.
[Parallel(n_jobs=-2)]: Using backend ThreadingBackend with 11 concurrent workers.
[Parallel(n_jobs=-2)]: Done   3 tasks      | elapsed:    1.5s
[Parallel(n_jobs=-2)]: Done  10 tasks      | elapsed:    1.6s
[Parallel(n_jobs=-2)]: Done  19 tasks      | elapsed:    2.1s
[Parallel(n_jobs=-2)]: Done  28 tasks      | elapsed:    2.5s
[Parallel(n_jobs=-2)]: Done  39 tasks      | elapsed:    3.0s
[Parallel(n_jobs=-2)]: Done  50 tasks      | elapsed:    3.4s
[Parallel(n_jobs=-2)]: Done  63 tasks      | elapsed:    3.9s
[Parallel(n_jobs=-2)]: Done  76 tasks      | elapsed:    4.4s
[Parallel(n_jobs=-2)]: Done  91 tasks      | elapsed:    5.4s
[Parallel(n_jobs=-2)]: Done 106 tasks      | elapsed:    6.6s
[Parallel(n_jobs=-2)]: Done 123 tasks      | elapsed:    8.4s
[Parallel(n_jobs=-2)]: Done 140 tasks      | elapsed:    9.8s
[Parallel(n_jobs=-2)]: Done 159 tasks      | elapsed:   12.0s
[Parallel(n_jobs=-2)]: Done 178 tasks      | elapsed:   12.9s
[Parallel(n_jobs=-2)]: Done 199 tasks      | elapsed:   14.1s
[Parallel(n_jobs=-2)]: Done 220 tasks      | elapsed:   15.4s
[Parallel(n_jobs=-2)]: Done 243 tasks      | elapsed:   17.7s
[Parallel(n_jobs=-2)]: Done 266 tasks      | elapsed:   20.0s
[Parallel(n_jobs=-2)]: Done 291 tasks      | elapsed:   23.3s
[Parallel(n_jobs=-2)]: Done 316 tasks      | elapsed:   25.7s
[Parallel(n_jobs=-2)]: Done 343 tasks      | elapsed:   28.8s
[Parallel(n_jobs=-2)]: Done 370 tasks      | elapsed:   31.5s
[Parallel(n_jobs=-2)]: Done 399 tasks      | elapsed:   34.1s
[Parallel(n_jobs=-2)]: Done 428 tasks      | elapsed:   35.4s
[Parallel(n_jobs=-2)]: Done 459 tasks      | elapsed:   36.7s
[Parallel(n_jobs=-2)]: Done 490 tasks      | elapsed:   37.9s
[Parallel(n_jobs=-2)]: Done 523 tasks      | elapsed:   39.6s
[Parallel(n_jobs=-2)]: Done 556 tasks      | elapsed:   41.7s
[Parallel(n_jobs=-2)]: Done 591 tasks      | elapsed:   43.9s
[Parallel(n_jobs=-2)]: Done 626 tasks      | elapsed:   45.6s
[Parallel(n_jobs=-2)]: Done 663 tasks      | elapsed:   47.3s
[Parallel(n_jobs=-2)]: Done 700 tasks      | elapsed:   49.0s
[Parallel(n_jobs=-2)]: Done 739 tasks      | elapsed:   50.9s
[Parallel(n_jobs=-2)]: Done 778 tasks      | elapsed:   52.7s
[Parallel(n_jobs=-2)]: Done 819 tasks      | elapsed:   54.6s
[Parallel(n_jobs=-2)]: Done 860 tasks      | elapsed:   56.3s
[Parallel(n_jobs=-2)]: Done 903 tasks      | elapsed:   58.3s
[Parallel(n_jobs=-2)]: Done 946 tasks      | elapsed:  1.0min
[Parallel(n_jobs=-2)]: Done 991 tasks      | elapsed:  1.0min
[Parallel(n_jobs=-2)]: Done 1036 tasks      | elapsed:  1.1min
[Parallel(n_jobs=-2)]: Done 1083 tasks      | elapsed:  1.1min
[Parallel(n_jobs=-2)]: Done 1130 tasks      | elapsed:  1.2min
[Parallel(n_jobs=-2)]: Done 1179 tasks      | elapsed:  1.2min
[Parallel(n_jobs=-2)]: Done 1228 tasks      | elapsed:  1.3min
[Parallel(n_jobs=-2)]: Done 1279 tasks      | elapsed:  1.3min
[Parallel(n_jobs=-2)]: Done 1330 tasks      | elapsed:  1.4min
[Parallel(n_jobs=-2)]: Done 1383 tasks      | elapsed:  1.4min
[Parallel(n_jobs=-2)]: Done 1436 tasks      | elapsed:  1.5min
[Parallel(n_jobs=-2)]: Done 1491 tasks      | elapsed:  1.5min
[Parallel(n_jobs=-2)]: Done 1546 tasks      | elapsed:  1.6min
[Parallel(n_jobs=-2)]: Done 1603 tasks      | elapsed:  1.7min
[Parallel(n_jobs=-2)]: Done 1660 tasks      | elapsed:  1.7min
[Parallel(n_jobs=-2)]: Using backend ThreadingBackend with 11 concurrent workers.
[Parallel(n_jobs=-2)]: Done 1719 tasks      | elapsed:  1.8min
[Parallel(n_jobs=-2)]: Done   3 tasks      | elapsed:    1.5s
[Parallel(n_jobs=-2)]: Done  10 tasks      | elapsed:    1.7s
[Parallel(n_jobs=-2)]: Done  19 tasks      | elapsed:    2.2s
[Parallel(n_jobs=-2)]: Done  28 tasks      | elapsed:    2.7s
[Parallel(n_jobs=-2)]: Done  39 tasks      | elapsed:    3.3s
[Parallel(n_jobs=-2)]: Done 1778 tasks      | elapsed:  1.8min
[Parallel(n_jobs=-2)]: Done  50 tasks      | elapsed:    3.8s
[Parallel(n_jobs=-2)]: Done  63 tasks      | elapsed:    4.5s
[Parallel(n_jobs=-2)]: Done  76 tasks      | elapsed:    5.2s
[Parallel(n_jobs=-2)]: Done  91 tasks      | elapsed:    6.0s
[Parallel(n_jobs=-2)]: Done 1839 tasks      | elapsed:  1.9min
[Parallel(n_jobs=-2)]: Done 106 tasks      | elapsed:    6.7s
[Parallel(n_jobs=-2)]: Done 123 tasks      | elapsed:    7.6s
[Parallel(n_jobs=-2)]: Done 140 tasks      | elapsed:    8.4s
[Parallel(n_jobs=-2)]: Done 159 tasks      | elapsed:    9.4s
[Parallel(n_jobs=-2)]: Done 1900 tasks      | elapsed:  1.9min
[Parallel(n_jobs=-2)]: Done 178 tasks      | elapsed:   10.4s
[Parallel(n_jobs=-2)]: Done 199 tasks      | elapsed:   11.7s
[Parallel(n_jobs=-2)]: Done 220 tasks      | elapsed:   13.1s
[Parallel(n_jobs=-2)]: Done 1963 tasks      | elapsed:  2.0min
[Parallel(n_jobs=-2)]: Done 243 tasks      | elapsed:   14.4s
[Parallel(n_jobs=-2)]: Done 266 tasks      | elapsed:   15.6s
[Parallel(n_jobs=-2)]: Done 2026 tasks      | elapsed:  2.0min
[Parallel(n_jobs=-2)]: Done 291 tasks      | elapsed:   17.0s
[Parallel(n_jobs=-2)]: Done 316 tasks      | elapsed:   18.2s
[Parallel(n_jobs=-2)]: Done 343 tasks      | elapsed:   19.6s
[Parallel(n_jobs=-2)]: Done 2091 tasks      | elapsed:  2.1min
[Parallel(n_jobs=-2)]: Done 370 tasks      | elapsed:   21.0s
[Parallel(n_jobs=-2)]: Done 399 tasks      | elapsed:   22.4s
[Parallel(n_jobs=-2)]: Done 2156 tasks      | elapsed:  2.1min
[Parallel(n_jobs=-2)]: Done 428 tasks      | elapsed:   24.0s
[Parallel(n_jobs=-2)]: Done 459 tasks      | elapsed:   25.7s
[Parallel(n_jobs=-2)]: Done 2223 tasks      | elapsed:  2.2min
[Parallel(n_jobs=-2)]: Done 490 tasks      | elapsed:   27.3s
[Parallel(n_jobs=-2)]: Done 523 tasks      | elapsed:   29.1s
[Parallel(n_jobs=-2)]: Done 556 tasks      | elapsed:   31.0s
[Parallel(n_jobs=-2)]: Done 2290 tasks      | elapsed:  2.3min
[Parallel(n_jobs=-2)]: Done 591 tasks      | elapsed:   32.8s
[Parallel(n_jobs=-2)]: Done 626 tasks      | elapsed:   34.7s
[Parallel(n_jobs=-2)]: Done 2359 tasks      | elapsed:  2.3min
[Parallel(n_jobs=-2)]: Done 663 tasks      | elapsed:   36.8s
[Parallel(n_jobs=-2)]: Done 2428 tasks      | elapsed:  2.4min
[Parallel(n_jobs=-2)]: Done 700 tasks      | elapsed:   38.6s
[Parallel(n_jobs=-2)]: Done 739 tasks      | elapsed:   40.7s
[Parallel(n_jobs=-2)]: Done 2499 tasks      | elapsed:  2.5min
[Parallel(n_jobs=-2)]: Done 778 tasks      | elapsed:   42.7s
[Parallel(n_jobs=-2)]: Done 819 tasks      | elapsed:   44.8s
[Parallel(n_jobs=-2)]: Done 2570 tasks      | elapsed:  2.5min
[Parallel(n_jobs=-2)]: Done 860 tasks      | elapsed:   47.2s
[Parallel(n_jobs=-2)]: Done 903 tasks      | elapsed:   49.9s
[Parallel(n_jobs=-2)]: Done 2643 tasks      | elapsed:  2.6min
[Parallel(n_jobs=-2)]: Done 946 tasks      | elapsed:   52.6s
[Parallel(n_jobs=-2)]: Done 2716 tasks      | elapsed:  2.7min
[Parallel(n_jobs=-2)]: Done 991 tasks      | elapsed:   54.8s
[Parallel(n_jobs=-2)]: Done 1036 tasks      | elapsed:   57.0s
[Parallel(n_jobs=-2)]: Done 2791 tasks      | elapsed:  2.7min
[Parallel(n_jobs=-2)]: Done 1083 tasks      | elapsed:   59.4s
[Parallel(n_jobs=-2)]: Done 1130 tasks      | elapsed:  1.0min
[Parallel(n_jobs=-2)]: Done 2866 tasks      | elapsed:  2.8min
[Parallel(n_jobs=-2)]: Done 1179 tasks      | elapsed:  1.1min
[Parallel(n_jobs=-2)]: Done 2943 tasks      | elapsed:  2.8min
[Parallel(n_jobs=-2)]: Done 1228 tasks      | elapsed:  1.1min
[Parallel(n_jobs=-2)]: Done 1279 tasks      | elapsed:  1.2min
[Parallel(n_jobs=-2)]: Done 3020 tasks      | elapsed:  2.9min
[Parallel(n_jobs=-2)]: Done 1330 tasks      | elapsed:  1.2min
[Parallel(n_jobs=-2)]: Done 3099 tasks      | elapsed:  3.0min
[Parallel(n_jobs=-2)]: Done 1383 tasks      | elapsed:  1.2min
[Parallel(n_jobs=-2)]: Done 1436 tasks      | elapsed:  1.3min
[Parallel(n_jobs=-2)]: Done 3178 tasks      | elapsed:  3.0min
[Parallel(n_jobs=-2)]: Done 1491 tasks      | elapsed:  1.3min
[Parallel(n_jobs=-2)]: Done 3259 tasks      | elapsed:  3.1min
[Parallel(n_jobs=-2)]: Done 1546 tasks      | elapsed:  1.4min
[Parallel(n_jobs=-2)]: Done 3340 tasks      | elapsed:  3.2min
[Parallel(n_jobs=-2)]: Done 1603 tasks      | elapsed:  1.5min
[Parallel(n_jobs=-2)]: Done 1660 tasks      | elapsed:  1.5min
[Parallel(n_jobs=-2)]: Done 3423 tasks      | elapsed:  3.3min
[Parallel(n_jobs=-2)]: Done 1719 tasks      | elapsed:  1.6min
[Parallel(n_jobs=-2)]: Done 3506 tasks      | elapsed:  3.4min
[Parallel(n_jobs=-2)]: Done 1778 tasks      | elapsed:  1.6min
[Parallel(n_jobs=-2)]: Done 3591 tasks      | elapsed:  3.5min
[Parallel(n_jobs=-2)]: Done 1839 tasks      | elapsed:  1.7min
[Parallel(n_jobs=-2)]: Done 3676 tasks      | elapsed:  3.6min
[Parallel(n_jobs=-2)]: Done 1900 tasks      | elapsed:  1.8min
[Parallel(n_jobs=-2)]: Done 1963 tasks      | elapsed:  1.9min
[Parallel(n_jobs=-2)]: Done 3763 tasks      | elapsed:  3.7min
[Parallel(n_jobs=-2)]: Done 2026 tasks      | elapsed:  2.0min
[Parallel(n_jobs=-2)]: Done 3850 tasks      | elapsed:  3.7min
[Parallel(n_jobs=-2)]: Done 2091 tasks      | elapsed:  2.0min
[Parallel(n_jobs=-2)]: Using backend ThreadingBackend with 11 concurrent workers.
[Parallel(n_jobs=-2)]: Done 3939 tasks      | elapsed:  3.8min
[Parallel(n_jobs=-2)]: Done   3 tasks      | elapsed:    1.9s
[Parallel(n_jobs=-2)]: Done 2156 tasks      | elapsed:  2.1min
[Parallel(n_jobs=-2)]: Done  10 tasks      | elapsed:    2.2s
[Parallel(n_jobs=-2)]: Done  19 tasks      | elapsed:    3.2s
[Parallel(n_jobs=-2)]: Done  28 tasks      | elapsed:    4.2s
[Parallel(n_jobs=-2)]: Done  39 tasks      | elapsed:    5.1s
[Parallel(n_jobs=-2)]: Done  50 tasks      | elapsed:    6.0s
[Parallel(n_jobs=-2)]: Done  63 tasks      | elapsed:    7.4s
[Parallel(n_jobs=-2)]: Done 2223 tasks      | elapsed:  2.2min
[Parallel(n_jobs=-2)]: Done 4028 tasks      | elapsed:  3.9min
[Parallel(n_jobs=-2)]: Done  76 tasks      | elapsed:    8.7s
[Parallel(n_jobs=-2)]: Done  91 tasks      | elapsed:    9.9s
[Parallel(n_jobs=-2)]: Done 106 tasks      | elapsed:   10.9s
[Parallel(n_jobs=-2)]: Done 123 tasks      | elapsed:   12.1s
[Parallel(n_jobs=-2)]: Done 140 tasks      | elapsed:   13.6s
[Parallel(n_jobs=-2)]: Done 2290 tasks      | elapsed:  2.3min
[Parallel(n_jobs=-2)]: Done 159 tasks      | elapsed:   14.6s
[Parallel(n_jobs=-2)]: Done 4119 tasks      | elapsed:  4.0min
[Parallel(n_jobs=-2)]: Done 178 tasks      | elapsed:   15.6s
[Parallel(n_jobs=-2)]: Done 199 tasks      | elapsed:   16.8s
[Parallel(n_jobs=-2)]: Done 2359 tasks      | elapsed:  2.3min
[Parallel(n_jobs=-2)]: Done 220 tasks      | elapsed:   18.2s
[Parallel(n_jobs=-2)]: Done 243 tasks      | elapsed:   19.9s
[Parallel(n_jobs=-2)]: Done 4210 tasks      | elapsed:  4.1min
[Parallel(n_jobs=-2)]: Done 266 tasks      | elapsed:   21.9s
[Parallel(n_jobs=-2)]: Done 2428 tasks      | elapsed:  2.4min
[Parallel(n_jobs=-2)]: Done 291 tasks      | elapsed:   24.1s
[Parallel(n_jobs=-2)]: Done 316 tasks      | elapsed:   25.6s
[Parallel(n_jobs=-2)]: Done 343 tasks      | elapsed:   27.9s
[Parallel(n_jobs=-2)]: Done 4303 tasks      | elapsed:  4.3min
[Parallel(n_jobs=-2)]: Done 2499 tasks      | elapsed:  2.5min
[Parallel(n_jobs=-2)]: Done 370 tasks      | elapsed:   29.3s
[Parallel(n_jobs=-2)]: Done 399 tasks      | elapsed:   31.6s
[Parallel(n_jobs=-2)]: Done 428 tasks      | elapsed:   33.7s
[Parallel(n_jobs=-2)]: Done 2570 tasks      | elapsed:  2.6min
[Parallel(n_jobs=-2)]: Done 4396 tasks      | elapsed:  4.4min
[Parallel(n_jobs=-2)]: Done 459 tasks      | elapsed:   36.1s
[Parallel(n_jobs=-2)]: Done 490 tasks      | elapsed:   38.3s
[Parallel(n_jobs=-2)]: Done 2643 tasks      | elapsed:  2.7min
[Parallel(n_jobs=-2)]: Done 523 tasks      | elapsed:   40.6s
[Parallel(n_jobs=-2)]: Done 4491 tasks      | elapsed:  4.5min
[Parallel(n_jobs=-2)]: Done 556 tasks      | elapsed:   43.2s
[Parallel(n_jobs=-2)]: Done 2716 tasks      | elapsed:  2.8min
[Parallel(n_jobs=-2)]: Done 591 tasks      | elapsed:   45.8s
[Parallel(n_jobs=-2)]: Done 626 tasks      | elapsed:   48.5s
[Parallel(n_jobs=-2)]: Done 4586 tasks      | elapsed:  4.6min
[Parallel(n_jobs=-2)]: Done 2791 tasks      | elapsed:  2.9min
[Parallel(n_jobs=-2)]: Done 663 tasks      | elapsed:   52.9s
[Parallel(n_jobs=-2)]: Done 700 tasks      | elapsed:   57.7s
[Parallel(n_jobs=-2)]: Done 2866 tasks      | elapsed:  3.0min
[Parallel(n_jobs=-2)]: Done 739 tasks      | elapsed:  1.0min
[Parallel(n_jobs=-2)]: Done 4683 tasks      | elapsed:  4.8min
[Parallel(n_jobs=-2)]: Done 778 tasks      | elapsed:  1.1min
[Parallel(n_jobs=-2)]: Done 2943 tasks      | elapsed:  3.2min
[Parallel(n_jobs=-2)]: Done 819 tasks      | elapsed:  1.2min
[Parallel(n_jobs=-2)]: Done 4780 tasks      | elapsed:  5.0min
[Parallel(n_jobs=-2)]: Done 860 tasks      | elapsed:  1.2min
[Parallel(n_jobs=-2)]: Done 3020 tasks      | elapsed:  3.3min
[Parallel(n_jobs=-2)]: Done 903 tasks      | elapsed:  1.3min
[Parallel(n_jobs=-2)]: Done 4879 tasks      | elapsed:  5.1min
[Parallel(n_jobs=-2)]: Done 946 tasks      | elapsed:  1.3min
[Parallel(n_jobs=-2)]: Done 3099 tasks      | elapsed:  3.4min
[Parallel(n_jobs=-2)]: Done 991 tasks      | elapsed:  1.4min
[Parallel(n_jobs=-2)]: Done 3178 tasks      | elapsed:  3.5min
[Parallel(n_jobs=-2)]: Done 1036 tasks      | elapsed:  1.4min
[Parallel(n_jobs=-2)]: Done 4978 tasks      | elapsed:  5.2min
[Parallel(n_jobs=-2)]: Done 1083 tasks      | elapsed:  1.5min
[Parallel(n_jobs=-2)]: Done 3259 tasks      | elapsed:  3.6min
[Parallel(n_jobs=-2)]: Done 1130 tasks      | elapsed:  1.6min
[Parallel(n_jobs=-2)]: Done 5079 tasks      | elapsed:  5.4min
[Parallel(n_jobs=-2)]: Done 1179 tasks      | elapsed:  1.6min
[Parallel(n_jobs=-2)]: Done 1228 tasks      | elapsed:  1.7min
[Parallel(n_jobs=-2)]: Done 5180 tasks      | elapsed:  5.5min
[Parallel(n_jobs=-2)]: Done 3340 tasks      | elapsed:  3.8min
[Parallel(n_jobs=-2)]: Done 1279 tasks      | elapsed:  1.8min
[Parallel(n_jobs=-2)]: Done 1330 tasks      | elapsed:  1.8min
[Parallel(n_jobs=-2)]: Done 3423 tasks      | elapsed:  3.9min
[Parallel(n_jobs=-2)]: Done 5283 tasks      | elapsed:  5.6min
[Parallel(n_jobs=-2)]: Done 1383 tasks      | elapsed:  1.9min
[Parallel(n_jobs=-2)]: Done 3506 tasks      | elapsed:  4.0min
[Parallel(n_jobs=-2)]: Done 1436 tasks      | elapsed:  1.9min
[Parallel(n_jobs=-2)]: Done 5386 tasks      | elapsed:  5.7min
[Parallel(n_jobs=-2)]: Done 1491 tasks      | elapsed:  2.0min
[Parallel(n_jobs=-2)]: Done 3591 tasks      | elapsed:  4.0min
[Parallel(n_jobs=-2)]: Done 1546 tasks      | elapsed:  2.0min
[Parallel(n_jobs=-2)]: Done 5491 tasks      | elapsed:  5.8min
[Parallel(n_jobs=-2)]: Done 3676 tasks      | elapsed:  4.2min
[Parallel(n_jobs=-2)]: Done 1603 tasks      | elapsed:  2.1min
[Parallel(n_jobs=-2)]: Done 1660 tasks      | elapsed:  2.2min
[Parallel(n_jobs=-2)]: Done 5596 tasks      | elapsed:  6.0min
[Parallel(n_jobs=-2)]: Done 3763 tasks      | elapsed:  4.2min
[Parallel(n_jobs=-2)]: Done 1719 tasks      | elapsed:  2.2min
[Parallel(n_jobs=-2)]: Done 5703 tasks      | elapsed:  6.1min
[Parallel(n_jobs=-2)]: Done 3850 tasks      | elapsed:  4.3min
[Parallel(n_jobs=-2)]: Done 1778 tasks      | elapsed:  2.3min
[Parallel(n_jobs=-2)]: Done 1839 tasks      | elapsed:  2.4min
[Parallel(n_jobs=-2)]: Done 3939 tasks      | elapsed:  4.4min
[Parallel(n_jobs=-2)]: Done 5810 tasks      | elapsed:  6.2min
[Parallel(n_jobs=-2)]: Done 1900 tasks      | elapsed:  2.4min
[Parallel(n_jobs=-2)]: Done 1963 tasks      | elapsed:  2.5min
[Parallel(n_jobs=-2)]: Done 4028 tasks      | elapsed:  4.6min
[Parallel(n_jobs=-2)]: Done 5919 tasks      | elapsed:  6.3min
/home/kojo/Code/hai-top-k/kenv/lib/python3.14/site-packages/joblib/externals/loky/process_executor.py:787: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  warnings.warn(
[Parallel(n_jobs=-2)]: Done 2026 tasks      | elapsed:  2.6min
[Parallel(n_jobs=-2)]: Done 4119 tasks      | elapsed:  4.7min

:

In [10]:
data = []
for item in res:
    rank_pairs, *rest = item
    for pair in rank_pairs:
        data.append((*pair, *rest))

df = pl.DataFrame(data, orient="row", schema=[
    "Human-Ranking", "Algo-Ranking", "Utility", "Distance", "Uses-Human-Utility", "Human-Beta", "Algorithm-Beta", "Algorithm-Alpha", "Algorithm-Sigma"
])

df

shape: (200, 9)
┌────────────┬───────────┬──────────┬──────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ Human-Rank ┆ Algo-Rank ┆ Utility  ┆ Distance ┆ … ┆ Human-Bet ┆ Algorithm ┆ Algorithm ┆ Algorithm │
│ ing        ┆ ing       ┆ ---      ┆ ---      ┆   ┆ a         ┆ -Beta     ┆ -Alpha    ┆ -Sigma    │
│ ---        ┆ ---       ┆ f64      ┆ i64      ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│ list[i64]  ┆ list[i64] ┆          ┆          ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪═══════════╪══════════╪══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ [6, 1, …   ┆ [1, 10, … ┆ 0.169857 ┆ 21       ┆ … ┆ 1.5       ┆ 1.5       ┆ 1.5       ┆ 1.5       │
│ 3]         ┆ 5]        ┆          ┆          ┆   ┆           ┆           ┆           ┆           │
│ [6, 1, …   ┆ [8, 5, …  ┆ 0.102781 ┆ 21       ┆ … ┆ 1.5       ┆ 1.5       ┆ 1.5       ┆ 1.5       │
│ 3]         ┆ 7]        ┆          ┆          ┆   ┆           ┆           ┆           ┆           │
│ [6, 1, …   ┆ [1, 10, … ┆ 0.075243 ┆ 21       ┆ … ┆ 1.5       ┆ 1.5       ┆ 0.0       ┆ 1.5       │
│ 3]         ┆ 5]        ┆          ┆          ┆   ┆           ┆           ┆           ┆           │
│ [6, 1, …   ┆ [8, 5, …  ┆ 0.087443 ┆ 21       ┆ … ┆ 1.5       ┆ 1.5       ┆ 0.0       ┆ 1.5       │
│ 3]         ┆ 7]        ┆          ┆          ┆   ┆           ┆           ┆           ┆           │
│ [6, 1, …   ┆ [1, 10, … ┆ 0.134605 ┆ 21       ┆ … ┆ 0.5       ┆ 1.5       ┆ 1.5       ┆ 1.5       │
│ 3]         ┆ 5]        ┆          ┆          ┆   ┆           ┆           ┆           ┆           │
│ …          ┆ …         ┆ …        ┆ …        ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ [6, 1, …   ┆ [6, 1, …  ┆ 0.799351 ┆ 15       ┆ … ┆ 1.5       ┆ 1.5       ┆ 0.0       ┆ 1.5       │
│ 3]         ┆ 7]        ┆          ┆          ┆   ┆           ┆           ┆           ┆           │
│ [6, 1, …   ┆ [8, 4, …  ┆ 0.098713 ┆ 15       ┆ … ┆ 0.5       ┆ 1.5       ┆ 1.5       ┆ 1.5       │
│ 3]         ┆ 3]        ┆          ┆          ┆   ┆           ┆           ┆           ┆           │
│ [6, 1, …   ┆ [6, 1, …  ┆ 0.679108 ┆ 15       ┆ … ┆ 0.5       ┆ 1.5       ┆ 1.5       ┆ 1.5       │
│ 3]         ┆ 7]        ┆          ┆          ┆   ┆           ┆           ┆           ┆           │
│ [6, 1, …   ┆ [8, 4, …  ┆ 0.079406 ┆ 15       ┆ … ┆ 0.5       ┆ 1.5       ┆ 0.0       ┆ 1.5       │
│ 3]         ┆ 3]        ┆          ┆          ┆   ┆           ┆           ┆           ┆           │
│ [6, 1, …   ┆ [6, 1, …  ┆ 0.670329 ┆ 15       ┆ … ┆ 0.5       ┆ 1.5       ┆ 0.0       ┆ 1.5       │
│ 3]         ┆ 7]        ┆          ┆          ┆   ┆           ┆           ┆           ┆           │
└────────────┴───────────┴──────────┴──────────┴───┴───────────┴───────────┴───────────┴───────────┘

ShapeError: data does not match the number of columns

In [28]:
import random

data = [
    ([random.randint(1, 1000), 7, 8, 2, 0, 3, 6, 9, 5, 4], [random.randint(1, 1000), 2, 0, 1, 8, 3, 6, 9, 5, 4], np.float64(0.1901257889260058), random.randint(23, 24), True, 1.5, 1.5, 0.85, 1.5)
    for _ in range(1000)
]

schema = [
    "Human-Ranking", "Algo-Ranking", "Utility", "Distance", "Uses-Human-Utility", "Human-Beta", "Algorithm-Beta", "Algorithm-Alpha", "Algorithm-Sigma"
]

df = pl.DataFrame(data, orient="row", schema=schema)

df

shape: (1_000, 9)
┌────────────┬───────────┬──────────┬──────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ Human-Rank ┆ Algo-Rank ┆ Utility  ┆ Distance ┆ … ┆ Human-Bet ┆ Algorithm ┆ Algorithm ┆ Algorithm │
│ ing        ┆ ing       ┆ ---      ┆ ---      ┆   ┆ a         ┆ -Beta     ┆ -Alpha    ┆ -Sigma    │
│ ---        ┆ ---       ┆ f64      ┆ i64      ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│ list[i64]  ┆ list[i64] ┆          ┆          ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪═══════════╪══════════╪══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ [683, 7, … ┆ [545, 2,  ┆ 0.190126 ┆ 24       ┆ … ┆ 1.5       ┆ 1.5       ┆ 0.85      ┆ 1.5       │
│ 4]         ┆ … 4]      ┆          ┆          ┆   ┆           ┆           ┆           ┆           │
│ [89, 7, …  ┆ [657, 2,  ┆ 0.190126 ┆ 23       ┆ … ┆ 1.5       ┆ 1.5       ┆ 0.85      ┆ 1.5       │
│ 4]         ┆ … 4]      ┆          ┆          ┆   ┆           ┆           ┆           ┆           │
│ [729, 7, … ┆ [964, 2,  ┆ 0.190126 ┆ 24       ┆ … ┆ 1.5       ┆ 1.5       ┆ 0.85      ┆ 1.5       │
│ 4]         ┆ … 4]      ┆          ┆          ┆   ┆           ┆           ┆           ┆           │
│ [675, 7, … ┆ [379, 2,  ┆ 0.190126 ┆ 23       ┆ … ┆ 1.5       ┆ 1.5       ┆ 0.85      ┆ 1.5       │
│ 4]         ┆ … 4]      ┆          ┆          ┆   ┆           ┆           ┆           ┆           │
│ [987, 7, … ┆ [422, 2,  ┆ 0.190126 ┆ 24       ┆ … ┆ 1.5       ┆ 1.5       ┆ 0.85      ┆ 1.5       │
│ 4]         ┆ … 4]      ┆          ┆          ┆   ┆           ┆           ┆           ┆           │
│ …          ┆ …         ┆ …        ┆ …        ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ [57, 7, …  ┆ [840, 2,  ┆ 0.190126 ┆ 23       ┆ … ┆ 1.5       ┆ 1.5       ┆ 0.85      ┆ 1.5       │
│ 4]         ┆ … 4]      ┆          ┆          ┆   ┆           ┆           ┆           ┆           │
│ [274, 7, … ┆ [134, 2,  ┆ 0.190126 ┆ 23       ┆ … ┆ 1.5       ┆ 1.5       ┆ 0.85      ┆ 1.5       │
│ 4]         ┆ … 4]      ┆          ┆          ┆   ┆           ┆           ┆           ┆           │
│ [141, 7, … ┆ [876, 2,  ┆ 0.190126 ┆ 23       ┆ … ┆ 1.5       ┆ 1.5       ┆ 0.85      ┆ 1.5       │
│ 4]         ┆ … 4]      ┆          ┆          ┆   ┆           ┆           ┆           ┆           │
│ [824, 7, … ┆ [666, 2,  ┆ 0.190126 ┆ 23       ┆ … ┆ 1.5       ┆ 1.5       ┆ 0.85      ┆ 1.5       │
│ 4]         ┆ … 4]      ┆          ┆          ┆   ┆           ┆           ┆           ┆           │
│ [10, 7, …  ┆ [613, 2,  ┆ 0.190126 ┆ 24       ┆ … ┆ 1.5       ┆ 1.5       ┆ 0.85      ┆ 1.5       │
│ 4]         ┆ … 4]      ┆          ┆          ┆   ┆           ┆           ┆           ┆           │
└────────────┴───────────┴──────────┴──────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [37]:
#import pyarrow.dataset as ds
import uuid

def path_provider(args: pl.FileProviderArgs):
    assert args.index_in_partition == 0

    return f"Distance_{args.partition_keys.cast(pl.String).item()}/{uuid.uuid4().hex}.parquet"

chunk_size = 499
chunk = []
for item in data:
    chunk.append(item)
    if len(chunk) >= chunk_size:
        df = pl.LazyFrame(chunk, orient="row", schema=schema)
        df.sink_parquet(pl.PartitionBy(
            "./data/diversity_utilities",
            key="Distance",
            file_path_provider=path_provider
        ))
        # ds.write_dataset(
        #     df.to_arrow(),
        #     base_dir="./data/diversity_utilities",
        #     format="parquet",
        #     partitioning=["Distance"],
        #     partitioning_flavor="hive",
        #     existing_data_behavior="overwrite_or_ignore"
        # )
        chunk.clear()

if len(chunk) > 0:
    df = pl.LazyFrame(chunk, orient="row", schema=schema)
    df.sink_parquet(pl.PartitionBy(
        "./data/diversity_utilities",
        key="Distance",
        file_path_provider=path_provider
    ))
    # ds.write_dataset(
    #     df.to_arrow(),
    #     base_dir="./data/diversity_utilities",
    #     format="parquet",
    #     partitioning=["Distance"],
    #     partitioning_flavor="hive",
    #     existing_data_behavior="overwrite_or_ignore"
    # )
    del chunk

In [13]:
df.write_parquet("./data/diversity_utilities", partition_by=["Distance"])

In [2]:
df = pl.read_parquet("./data/diversity_utilities")
df

shape: (11_127_152, 9)
┌────────────┬───────────┬──────────┬──────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ Human-Rank ┆ Algo-Rank ┆ Utility  ┆ Distance ┆ … ┆ Human-Bet ┆ Algorithm ┆ Algorithm ┆ Algorithm │
│ ing        ┆ ing       ┆ ---      ┆ ---      ┆   ┆ a         ┆ -Beta     ┆ -Alpha    ┆ -Sigma    │
│ ---        ┆ ---       ┆ f64      ┆ i64      ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│ list[i64]  ┆ list[i64] ┆          ┆          ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪═══════════╪══════════╪══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ [5, 8, …   ┆ [5, 8, …  ┆ 0.782676 ┆ 0        ┆ … ┆ 1.5       ┆ 1.5       ┆ 1.5       ┆ 1.5       │
│ 10]        ┆ 10]       ┆          ┆          ┆   ┆           ┆           ┆           ┆           │
│ [8, 3, …   ┆ [8, 3, …  ┆ 0.776962 ┆ 0        ┆ … ┆ 1.5       ┆ 1.5       ┆ 1.5       ┆ 1.5       │
│ 10]        ┆ 10]       ┆          ┆          ┆   ┆           ┆           ┆           ┆           │
│ [8, 3, …   ┆ [8, 3, …  ┆ 0.776905 ┆ 0        ┆ … ┆ 1.5       ┆ 1.5       ┆ 1.5       ┆ 1.5       │
│ 7]         ┆ 7]        ┆          ┆          ┆   ┆           ┆           ┆           ┆           │
│ [8, 3, …   ┆ [8, 3, …  ┆ 0.776905 ┆ 0        ┆ … ┆ 1.5       ┆ 1.5       ┆ 1.5       ┆ 1.5       │
│ 7]         ┆ 7]        ┆          ┆          ┆   ┆           ┆           ┆           ┆           │
│ [2, 8, …   ┆ [2, 8, …  ┆ 0.776727 ┆ 0        ┆ … ┆ 1.5       ┆ 1.5       ┆ 1.5       ┆ 1.5       │
│ 10]        ┆ 10]       ┆          ┆          ┆   ┆           ┆           ┆           ┆           │
│ …          ┆ …         ┆ …        ┆ …        ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ [6, 4, …   ┆ [6, 8, …  ┆ 0.673619 ┆ 9        ┆ … ┆ 0.5       ┆ 1.5       ┆ 1.5       ┆ 1.5       │
│ 1]         ┆ 2]        ┆          ┆          ┆   ┆           ┆           ┆           ┆           │
│ [6, 4, …   ┆ [6, 8, …  ┆ 0.673619 ┆ 9        ┆ … ┆ 0.5       ┆ 1.5       ┆ 1.5       ┆ 1.5       │
│ 1]         ┆ 5]        ┆          ┆          ┆   ┆           ┆           ┆           ┆           │
│ [6, 4, …   ┆ [8, 6, …  ┆ 0.53873  ┆ 9        ┆ … ┆ 0.5       ┆ 1.5       ┆ 1.5       ┆ 1.5       │
│ 1]         ┆ 5]        ┆          ┆          ┆   ┆           ┆           ┆           ┆           │
│ [6, 4, …   ┆ [6, 8, …  ┆ 0.673619 ┆ 9        ┆ … ┆ 0.5       ┆ 1.5       ┆ 1.5       ┆ 1.5       │
│ 1]         ┆ 5]        ┆          ┆          ┆   ┆           ┆           ┆           ┆           │
│ [6, 4, …   ┆ [8, 6, …  ┆ 0.53873  ┆ 9        ┆ … ┆ 0.5       ┆ 1.5       ┆ 1.5       ┆ 1.5       │
│ 1]         ┆ 2]        ┆          ┆          ┆   ┆           ┆           ┆           ┆           │
└────────────┴───────────┴──────────┴──────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [3]:
distance_counts = df["Distance"].value_counts()

with pl.Config(tbl_rows=-1):
    print(distance_counts)

shape: (6, 2)
┌──────────┬─────────┐
│ Distance ┆ count   │
│ ---      ┆ ---     │
│ i64      ┆ u32     │
╞══════════╪═════════╡
│ 45       ┆ 32      │
│ 0        ┆ 640     │
│ 27       ┆ 2854704 │
│ 18       ┆ 6214392 │
│ 9        ┆ 1855496 │
│ 36       ┆ 201888  │
└──────────┴─────────┘